### ISSUE TITLE
Question about usage.

### ISSUE THREAD

**Issue by devshepel** [alddesign/cyberpunk-css#2]
First of all, you did a solid great job. I'm delighted.

I want to develop new game in sci-fi/cyberpunk setting. Since you don't provided license, could I ask to use your library, may be even if at some point I may go to release.

**Comment by alddesign** [comment]
Hello, Sir. Thanks a lot for this feedback.
Regarding your request: Of course, feel free to use it however you like. Im not really familiar with licensing, could you suggest me a good free-to-use license. Maybe one that just requires to mention me/this repo when using it?

**Comment by devshepel** [comment]
Hello, here's [video](https://www.youtube.com/watch?v=8Dm7XXvtqXI) how to add licence with selected from GitHub templates. I would suggest to use MIT licence, seems it's containing requirements to mention author:
<img width="1279" alt="Screenshot 2024-11-04 at 22 46 35" src="https://github.com/user-attachments/assets/47314dca-fce9-4fd5-b7e2-851f280907bd">
